// <auto-generated />
namespace eCademy.NUh16.PhotoShare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CascaseDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CascaseDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201802180524591_CascaseDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
